#!/usr/bin/env node
/**
 * Builds the self-contained Shopify email templates in ../templates/<lang>/ from ../src.
 * Shopify notifications cannot include files, so every shared block is inlined here.
 *
 * Placeholders: [[key]] copy from strings/<lang>.json (template section, then "common"),
 * [[c.name]] colour and [[s.name]] style from tokens.json, [[> partial]] a file from
 * src/partials (partial.<lang>.liquid wins over partial.liquid).
 *
 *   node dev/build.mjs          write templates/<lang>/*.liquid and templates/SUBJECTS.md
 *   node dev/build.mjs --check  exit 1 if the written templates are out of date
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(here, '..');
export const SRC = path.join(ROOT, 'src');
export const OUT = path.join(ROOT, 'templates');
export const LANGS = ['en', 'ar'];
export const TEMPLATES = [
  'order_confirmation',
  'shipping_confirmation',
  'shipping_update',
  'out_for_delivery',
  'delivered',
  'order_cancelled',
  'abandoned_checkout',
  'customer_account_invite',
  'customer_account_welcome',
  'customer_password_reset',
];

const readJSON = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));

function partial(name, lang) {
  for (const file of [`${name}.${lang}.liquid`, `${name}.liquid`]) {
    const full = path.join(SRC, 'partials', file);
    if (fs.existsSync(full)) return fs.readFileSync(full, 'utf8').replace(/\s+$/, '');
  }
  throw new Error(`unknown partial "${name}"`);
}

export function buildOne(name, lang) {
  const tokens = readJSON(path.join(SRC, 'tokens.json'));
  const strings = readJSON(path.join(SRC, 'strings', `${lang}.json`));
  if (!strings[name]) throw new Error(`strings/${lang}.json has no "${name}" section`);
  const copy = { ...strings.common, ...strings[name] };
  const lookup = (key) => {
    if (key.startsWith('c.') && key.slice(2) in tokens.c) return tokens.c[key.slice(2)];
    if (key.startsWith('s.') && key.slice(2) in tokens.s) return tokens.s[key.slice(2)];
    if (key in copy) return copy[key];
    throw new Error(`${lang}/${name}: unknown placeholder [[${key}]]`);
  };
  let text = fs.readFileSync(path.join(SRC, 'templates', `${name}.liquid`), 'utf8');
  for (let pass = 0; pass < 20 && text.includes('[['); pass += 1) {
    text = text.replace(/\[\[\s*(>)?\s*([\w.]+)\s*\]\]/g, (_, include, key) => (include ? partial(key, lang) : lookup(key)));
  }
  if (text.includes('[[')) throw new Error(`${lang}/${name}: unresolved placeholders (include cycle?)`);
  text = text.replace(/[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n').trim() + '\n';
  return { name, lang, subject: copy.subject, notification: copy.notification, body: text, file: path.join(OUT, lang, `${name}.liquid`) };
}

export function build() {
  return LANGS.flatMap((lang) => TEMPLATES.map((name) => buildOne(name, lang)));
}

export function subjectsMarkdown(built) {
  const rows = TEMPLATES.map((name) => {
    const en = built.find((b) => b.name === name && b.lang === 'en');
    const ar = built.find((b) => b.name === name && b.lang === 'ar');
    return `| ${en.notification} | \`${name}.liquid\` | ${en.subject} | ${ar.subject} |`;
  });
  return [
    '# Email subjects / عناوين الإيميلات',
    '',
    'Generated by `dev/build.mjs`. Paste the subject into **Email subject** (English: *Edit code*; Arabic: *Localize*).',
    '',
    '| Shopify notification | File | English subject | Arabic subject |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

function main() {
  const built = build();
  const outputs = [...built.map((b) => [b.file, b.body]), [path.join(OUT, 'SUBJECTS.md'), subjectsMarkdown(built)]];
  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([file, body]) => !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== body);
    if (stale.length) {
      console.error(`Stale templates (run node dev/build.mjs):\n${stale.map(([f]) => `  ${path.relative(ROOT, f)}`).join('\n')}`);
      process.exit(1);
    }
    console.log(`templates up to date (${built.length} files)`);
    return;
  }
  for (const [file, body] of outputs) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
  }
  for (const b of built) console.log(`${path.relative(ROOT, b.file).padEnd(46)} ${String(Buffer.byteLength(b.body)).padStart(6)} B`);
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) main();
